"""autogenerated by genmsg_py from PingerArray.msg. Do not edit."""
import roslib.message
import struct

import sonar_node.msg

class PingerArray(roslib.message.Message):
  _md5sum = "fd64935a04f55a3dfcff9fa3975c5353"
  _type = "sonar_node/PingerArray"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """sonar_node/Pinger[] Pingers

================================================================================
MSG: sonar_node/Pinger
int8 Id           # 0 is correct pinger, 1 is incorrect pinger
float64 Heading
float64 Magnitude
float64 TimeSince

"""
  __slots__ = ['Pingers']
  _slot_types = ['sonar_node/Pinger[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       Pingers
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(PingerArray, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.Pingers is None:
        self.Pingers = []
    else:
      self.Pingers = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      length = len(self.Pingers)
      buff.write(_struct_I.pack(length))
      for val1 in self.Pingers:
        _x = val1
        buff.write(_struct_b3d.pack(_x.Id, _x.Heading, _x.Magnitude, _x.TimeSince))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.Pingers = []
      for i in xrange(0, length):
        val1 = sonar_node.msg.Pinger()
        _x = val1
        start = end
        end += 25
        (_x.Id, _x.Heading, _x.Magnitude, _x.TimeSince,) = _struct_b3d.unpack(str[start:end])
        self.Pingers.append(val1)
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      length = len(self.Pingers)
      buff.write(_struct_I.pack(length))
      for val1 in self.Pingers:
        _x = val1
        buff.write(_struct_b3d.pack(_x.Id, _x.Heading, _x.Magnitude, _x.TimeSince))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.Pingers = []
      for i in xrange(0, length):
        val1 = sonar_node.msg.Pinger()
        _x = val1
        start = end
        end += 25
        (_x.Id, _x.Heading, _x.Magnitude, _x.TimeSince,) = _struct_b3d.unpack(str[start:end])
        self.Pingers.append(val1)
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_b3d = struct.Struct("<b3d")
