"""autogenerated by genmsg_py from Pinger.msg. Do not edit."""
import roslib.message
import struct


class Pinger(roslib.message.Message):
  _md5sum = "49d3e57ff39f4b02d41f58af18abc775"
  _type = "sonar_node/Pinger"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int8 Id           # 0 is correct pinger, 1 is incorrect pinger
float64 Heading
float64 Magnitude
float64 TimeSince

"""
  __slots__ = ['Id','Heading','Magnitude','TimeSince']
  _slot_types = ['int8','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       Id,Heading,Magnitude,TimeSince
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(Pinger, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.Id is None:
        self.Id = 0
      if self.Heading is None:
        self.Heading = 0.
      if self.Magnitude is None:
        self.Magnitude = 0.
      if self.TimeSince is None:
        self.TimeSince = 0.
    else:
      self.Id = 0
      self.Heading = 0.
      self.Magnitude = 0.
      self.TimeSince = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_b3d.pack(_x.Id, _x.Heading, _x.Magnitude, _x.TimeSince))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.Id, _x.Heading, _x.Magnitude, _x.TimeSince,) = _struct_b3d.unpack(str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_b3d.pack(_x.Id, _x.Heading, _x.Magnitude, _x.TimeSince))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.Id, _x.Heading, _x.Magnitude, _x.TimeSince,) = _struct_b3d.unpack(str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_b3d = struct.Struct("<b3d")
